### ISSUE TITLE
Github action fails on PR based on branches with single commit

### ISSUE THREAD

**Issue by pjanuario** [Madrapps/jacoco-report#13]
Github action fails on PR based on branches with single commit

When I open a PR with a single commit change, the action will fail with the following error:

```
Run madrapps/jacoco-report@v1.2
  with:
    paths: XXXXX/build/reports/jacoco/test/jacocoTestReport.xml
  
    token: ***
    min-coverage-overall: 80
    min-coverage-changed-files: 80
    title: Code Coverage
    debug-mode: false
  env:
    JAVA_HOME: /work/_tool/Java_Adopt_jdk/11.0.13-8/x64
Event is push
base sha: 0000000000000000000000000000000000000000
head sha: eb747d0f83b61843524f8618bb2ced79d7dc3ef4
Error: HttpError: Not Found

```

This seemed to be caused by a change made in checkout@v2 that no longer have the base sha in this cases. Wondering if anyone found a workaround for this?

```
name: "CI - Harvesters"
on:
  push:
    paths:
      - "my-project/**"
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: [ self-hosted, linux, dev ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path:  |
            ~/my-project/.gradle/caches
            ~/my-project/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: cd my-project && chmod +x gradlew
      - name: Analyze code formatting
        run: cd my-project && ./gradlew ktlintCheck
      - name: Build artifact
        run: cd my-project && ./gradlew assemble
      - name: Run tests
        run: cd my-project && ./gradlew test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: my-project/build/test-results/**/*.xml
      # - name: Publish coverage report to PR
      #   id: jacoco
      #   uses: madrapps/jacoco-report@v1.2
      #   with:
      #     paths: |
      #       ${{ github.workspace }}/my-project/build/reports/jacoco/test/jacocoTestReport.xml
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     min-coverage-overall: "80"
      #     min-coverage-changed-files: "80"
      #     title: Code Coverage
      # - name: Get the Coverage info
      #   run: |
      #     echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
      #     echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

```
