### ISSUE TITLE
Example in README uses 'paths', not 'path'

### ISSUE THREAD

**Issue by aSemy** [Madrapps/jacoco-report#22]
https://github.com/Madrapps/jacoco-report/blob/7a334255fbce42f385d7567c25d986a9c62e2971/README.md?plain=1#L51-L55

This produces an error

```
Warning: Unexpected input(s) 'paths', valid inputs are ['path', 'token', 'min-coverage-overall', 'min-coverage-changed-files']
```

**Comment by thsaravana** [comment]
Which version of the action are you using? `path` was replaced with `paths` in `v1.2`. Could you try using the action with `v1.2` ?

**Comment by aSemy** [comment]
I was using v1 (no minor version) so this probably used v1.1 so the problem is probably fixed now :)

```yaml
      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1
        if: ${{ always() }}
        continue-on-error: true
        with:
          path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
```
