### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '$')

### ISSUE THREAD

**Issue by chen-ni** [Madrapps/jacoco-report#39]
Hi, I'm running with the following config:

```
      - name: Add coverage to PR
        id: jacoco-1
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/path/to/report (real path omitted)
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
```

Got this error:
```
Run madrapps/jacoco-report@v1.3
  with:
    paths: *** (omitted)
    token: ***
    min-coverage-overall: 40
    min-coverage-changed-files: 60
    update-comment: false
    debug-mode: false
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64
Event is pull_request
base sha: 9dc14dc57fb9af092925b88dfa75011e8d1e701d
head sha: 1a3c428addd60dc8edd53b8f8700497115d9f188
Error: TypeError: Cannot read properties of undefined (reading '$')
```

Also tried `uses: madrapps/jacoco-report@main` as suggested by @thsaravana here: https://github.com/Madrapps/jacoco-report/issues/15 but didn't work either.

Could you please help, thanks.
