### ISSUE TITLE
Support for multiple Coverage reports

### ISSUE THREAD

**Issue by thsaravana** [Madrapps/jacoco-report#4]
In a multi module project, JaCoCo reports are generated in every module. But the action currently support only a single report via `path` input.
Add support so that multiple reports can be added as a comma separated value in `path`.

Reference: https://medium.com/madrapps/jacoco-single-coverage-report-for-multi-module-projects-2fec45f4263a

**Comment by CesarT3333** [comment]
would it be possible to add a description input to the modules?
like this:

```
with:
  description: Module A
  path: ${{ github.workspace }}/gateway/build/reports/jacoco/test/jacocoTestReport.xml
  token: ${{ secrets.GITHUB_TOKEN }}
  min-coverage-overall: 90
  min-coverage-changed-files: 60
```

![Captura de tela de 2021-08-31 18-56-12](https://user-images.githubusercontent.com/20017223/131581072-20695e69-a437-4430-b0d4-ef86bfae70ad.png)
